dist: bionic
language: crystal

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools
      - libevent-dev

install:
  # - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  # - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  # - sudo apt-get -qq update
  # - sudo apt-get install -y mongodb-org=4.2.7
  - wget https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.7_amd64.deb
  - sudo dpkg -i mongodb-org-server_4.2.7_amd64.deb
  - python3 -m pip install mtools[all]

before_script:
  - shards install --ignore-crystal-version
  - which mongod
  - mongod --version

script:
  - crystal spec