dist: bionic
language: minimal

env:
  matrix:
    - MONGODB_VERSION=4.0.23 MONGODB_RELEASE=4.0
    - MONGODB_VERSION=4.2.13  MONGODB_RELEASE=4.2
    # - MONGODB_VERSION=4.4.4  MONGODB_RELEASE=4.4

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools
      - libevent-dev

install:
  - curl -fsSL https://crystal-lang.org/install.sh | sudo bash
  - wget https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/${MONGODB_RELEASE}/multiverse/binary-amd64/mongodb-org-server_${MONGODB_VERSION}_amd64.deb
  - sudo dpkg -i mongodb-org-server_${MONGODB_VERSION}_amd64.deb
  - wget https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/${MONGODB_RELEASE}/multiverse/binary-amd64/mongodb-org-mongos_${MONGODB_VERSION}_amd64.deb
  - sudo dpkg -i mongodb-org-mongos_${MONGODB_VERSION}_amd64.deb
  - python3 -m pip install mtools[all]

before_script:
  - shards install
  - which mongod
  - mongod --version

script:
  - crystal spec --tag single
  - crystal spec --tag replicaset
  - crystal spec --tag sharded
  - crystal spec --tag sharded_multiple_mongos
